// Constants for game mechanics and limits

export const ENERGY_LIMITS = {
  OD_ENERGY_MAX: 800,
  OVERFLOW_ENERGY_MAX: 800,
};

export const WEEKLY_LIMITS = {
  EXPEDITION: 35,
  TRANSCENDENCE: 28,
  AWAKENING: 3,
  PET: 7,
  ENERGY_BOUGHT: 7,
  ENERGY_CRAFTED: 7,
};

export const DIMINISHING_RETURNS = {
  TIER_1_LIMIT: 54, // 0-54: 100%
  TIER_2_LIMIT: 62, // 55-62: 80%
  // 63+: 60%
  TIER_1_FACTOR: 1.0,
  TIER_2_FACTOR: 0.8,
  TIER_3_FACTOR: 0.6,
};

export const CRAFTING_COSTS = {
  ENERGY_CRAFT_BASE_FEE: 50000,
  AETHER_MULTIPLIER: 25,
  HIGH_PURITY_AETHER_MULTIPLIER: 5,
  PURE_AETHER_MULTIPLIER: 5,
  CRAFT_BATCH_SIZE: 7,
};

export const ENERGY_BUY_AMOUNT = 700000;
